### ISSUE TITLE
Adding value with existing API information

### ISSUE THREAD

**Issue by bnb** [harksys/HawkEye#16] opened 2017-01-06 04:22 UTC
Looking through the list of filters for notifications, I think there's some definite value that can be added by working enabling that information to be displayed _outside_ of the filters.

For example, if there's a PR that I authored and there's a state change on it (two filters in `Reasons`), it would be sweet to be able to know that by looking at the notification rather than needing to find it out by selecting the correct filters and interpreting the notifications that are displayed based on those filters.

**Comment by andrewhathaway** [comment] 2017-01-06 10:45
Sure, this can be looked at. This would require pulling in the full Issue/PR and seeing what data we have available. I also worry about cluttering the initial feed, so would be interesting to see how to does this without getting too messy.

I currently have an idea of being able to double click on the notification which will pull in all the information you mentioned above, and more, including the thread etc.

**Comment by andrewhathaway** [comment] 2017-01-06 16:11
Closing this as a dupe of #11.

**Closed by andrewhathaway** 2017-01-06 16:11 UTC
Labels: Feature Request, Help Wanted
